version: '2'

networks:
  default:
    external: true
    name: finance_default

services:

  studentdb:
    image: mariadb
    restart: always
    volumes:
      - ./migrations/mysql-migrations.sql:/docker-entrypoint-initdb.d/mysql-mysql-migrations.sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - default
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      timeout: 2s
      retries: 10

  studentapp:
    image: tvergilio/student:1.0
    environment:
      spring.datasource.url: jdbc:mariadb://studentdb:3306/${DB_NAME}
      spring.datasource.username: ${DB_APPLICATION_USER}
      spring.datasource.password: ${DB_APPLICATION_PASSWORD}
    ports:
      - "8090:8090"
    expose:
      - "8090"
    depends_on:
      studentdb:
        condition: service_healthy
    networks:
      - default